default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: bella_beauty_development

test:
  <<: *default
  database: bella_beauty_test

production:
  <<: *default
  database: bella_beauty_production
  username: bella_beauty
  password: <%= ENV['BELLA_BEAUTY_DATABASE_PASSWORD'] %>
